const companyData = [
  {
    "id": "dpsp",
    "empresa_nome": "Drogaria São Paulo — Grupo DPSP",
    "empresa_setor": "Varejo Farmacêutico",
    "decisor_nome": "Luis Janssen",
    "decisor_cargo": "Diretor de TI",
    "decisor_tempo_empresa": "Desde dezembro de 2023",
    "faturamento_anual": "Acima de R$ 15 Bi",
    "orcamento_ti": "R$ 100–200 MM",
    "ti_percentual_receita": "1,7%",
    "crescimento_orcamento": "Manutenção",
    "nivel_hierarquico": "Vice-presidência",
    "reporte_ti": "CEO/Presidência",
    "perspectiva_negocio": "Crescimento",
    "modelo_compra": "RFP/concorrência estruturada",
    "trimestre_investimento": "Q2 2026",
    "desafios_top6": ["Atrair e engajar talentos", "IA/GenAI", "Automatizar processos", "Priorizar portfólio", "Provar ROI", "Cibersegurança"],
    "dificuldade_talentos": "Sim (contratação)",
    "maturidade_inovacao": "Emergente",
    "temas_sem_fornecedor": "Vários projetos de IA e automação"
  },
  {
    "id": "athena",
    "empresa_nome": "Athena Saúde",
    "empresa_setor": "Saúde",
    "decisor_nome": "Antonio Vanderlei Soares",
    "decisor_cargo": "Líder de TI",
    "decisor_tempo_empresa": "Desde agosto de 2022",
    "faturamento_anual": "R$ 4,1–5 Bi",
    "orcamento_ti": "R$ 100–200 MM",
    "ti_percentual_receita": "2,0%",
    "crescimento_orcamento": "Até +10%",
    "nivel_hierarquico": "Diretoria",
    "reporte_ti": "CFO/Financeiro",
    "perspectiva_negocio": "Crescimento",
    "modelo_compra": "Canais/parceiros credenciados",
    "trimestre_investimento": "Q3 2026",
    "desafios_top6": ["IA/GenAI", "SRE/Observabilidade", "Governança/compliance", "Integração TI+negócio", "Arquiteturas híbridas/multicloud", "Provar ROI"],
    "dificuldade_talentos": "Não informado",
    "maturidade_inovacao": "Não informado",
    "temas_sem_fornecedor": "IA/ML, IA Generativa, APIs/integração"
  },
  {
    "id": "axa",
    "empresa_nome": "AXA no Brasil",
    "empresa_setor": "Seguros",
    "decisor_nome": "Bruno Porte",
    "decisor_cargo": "Líder de TI",
    "decisor_tempo_empresa": "Desde janeiro de 2023",
    "faturamento_anual": "Não informado",
    "orcamento_ti": "R$ 80–100 MM",
    "ti_percentual_receita": "5,0%",
    "crescimento_orcamento": "+10% a +20%",
    "nivel_hierarquico": "Não informado",
    "reporte_ti": "CEO/Presidência",
    "perspectiva_negocio": "Não informado",
    "modelo_compra": "RFP/concorrência estruturada",
    "trimestre_investimento": "Q2 2026",
    "desafios_top6": ["IA/GenAI", "Automatizar processos", "Cultura de inovação", "Qualidade de dados", "Integração TI+negócio", "Provar ROI"],
    "dificuldade_talentos": "Não informado",
    "maturidade_inovacao": "Não informado",
    "temas_sem_fornecedor": "Não informado"
  },
  {
    "id": "ocq",
    "empresa_nome": "Grupo Oswaldo Cruz Química",
    "empresa_setor": "Química",
    "decisor_nome": "Claudia Ferraz",
    "decisor_cargo": "Líder de TI",
    "decisor_tempo_empresa": "Desde 2020",
    "faturamento_anual": "Não informado",
    "orcamento_ti": "R$ 100–200 MM",
    "ti_percentual_receita": "2,0%",
    "crescimento_orcamento": "Até +10%",
    "nivel_hierarquico": "Vice-presidência",
    "reporte_ti": "CEO/Presidência",
    "perspectiva_negocio": "Não informado",
    "modelo_compra": "RFP/concorrência estruturada",
    "trimestre_investimento": "Q1 2026",
    "desafios_top6": ["IA/GenAI", "Talentos", "Automatizar processos", "Cultura de inovação", "Governança/compliance", "Provar ROI"],
    "dificuldade_talentos": "Sim (contratação e engajamento)",
    "maturidade_inovacao": "Escalonada",
    "temas_sem_fornecedor": "Cibersegurança, IA, automação"
  },
  {
    "id": "louis_dreyfus",
    "empresa_nome": "Louis Dreyfus",
    "empresa_setor": "Agro / Commodities",
    "decisor_nome": "Edson Alves",
    "decisor_cargo": "Líder de TI",
    "decisor_tempo_empresa": "Desde outubro de 2014",
    "faturamento_anual": "R$ 500–600 MM",
    "orcamento_ti": "R$ 50–80 MM",
    "ti_percentual_receita": "5,0%",
    "crescimento_orcamento": "Redução 10–20%",
    "nivel_hierarquico": "Gerência",
    "reporte_ti": "CEO/Presidência",
    "perspectiva_negocio": "Volátil/Incerta",
    "modelo_compra": "RFP/concorrência estruturada",
    "trimestre_investimento": "Não informado",
    "desafios_top6": ["Talentos", "Automatizar processos", "Cultura de inovação", "Integração TI+negócio", "Posicionar TI como estratégica", "Provar ROI"],
    "dificuldade_talentos": "Não informado",
    "maturidade_inovacao": "Inicial",
    "temas_sem_fornecedor": "Dados/IA, automação, cibersegurança"
  },
  {
    "id": "adimax",
    "empresa_nome": "Adimax Pet",
    "empresa_setor": "Indústria Pet",
    "decisor_nome": "Fernando Rostock",
    "decisor_cargo": "Head de TI",
    "decisor_tempo_empresa": "Desde abril de 2025",
    "faturamento_anual": "R$ 5,1–6 Bi",
    "orcamento_ti": "Não informado",
    "ti_percentual_receita": "1,0%",
    "crescimento_orcamento": "Acima de +30%",
    "nivel_hierarquico": "Vice-presidência",
    "reporte_ti": "CEO/Presidência",
    "perspectiva_negocio": "Crescimento",
    "modelo_compra": "RFP/concorrência estruturada",
    "trimestre_investimento": "Q2 2026",
    "desafios_top6": ["IA/GenAI", "Automatizar processos", "Cultura de inovação", "Qualidade de dados", "Integração TI+negócio", "Provar ROI"],
    "dificuldade_talentos": "Sim (escassez, soft skills, disputa salarial)",
    "maturidade_inovacao": "Emergente",
    "temas_sem_fornecedor": "Hiperautomação, vários temas de maturidade"
  },
  {
    "id": "cnu",
    "empresa_nome": "Central Nacional Unimed",
    "empresa_setor": "Saúde / Seguros",
    "decisor_nome": "Humberto Shida",
    "decisor_cargo": "CIO / Responsável por Operações, TI, Dados e Inovação",
    "decisor_tempo_empresa": "Desde 2020",
    "faturamento_anual": "Acima de R$ 15 Bi",
    "orcamento_ti": "R$ 200–300 MM",
    "ti_percentual_receita": "1,2%",
    "crescimento_orcamento": "+10% a +20%",
    "nivel_hierarquico": "Vice-presidência",
    "reporte_ti": "CEO/Presidência",
    "perspectiva_negocio": "Crescimento",
    "modelo_compra": "RFP/concorrência estruturada",
    "trimestre_investimento": "Q3 2026",
    "desafios_top6": ["IA/GenAI", "Talentos", "SRE/Observabilidade", "CX/EX", "Transformação digital", "Priorizar portfólio"],
    "dificuldade_talentos": "Não (mas escassez de perfis e senioridade)",
    "maturidade_inovacao": "Escalonada",
    "temas_sem_fornecedor": "Nuvem pública (não definido)"
  },
  {
    "id": "total_express",
    "empresa_nome": "Total Express",
    "empresa_setor": "Logística",
    "decisor_nome": "Juliano De Conti",
    "decisor_cargo": "CIO",
    "decisor_tempo_empresa": "Desde 2021",
    "faturamento_anual": "Não informado",
    "orcamento_ti": "Não informado",
    "ti_percentual_receita": "3,0%",
    "crescimento_orcamento": "Redução",
    "nivel_hierarquico": "Não informado",
    "reporte_ti": "CEO/Presidência",
    "perspectiva_negocio": "Não informado",
    "modelo_compra": "Não informado",
    "trimestre_investimento": "Não informado",
    "desafios_top6": ["IA/GenAI", "SRE/Observabilidade", "Modernizar legados", "Híbrido/multicloud", "Cibersegurança", "Provar ROI"],
    "dificuldade_talentos": "Sim (disputa salarial, flexibilidade, localização)",
    "maturidade_inovacao": "Estruturada",
    "temas_sem_fornecedor": "Não informado"
  },
  {
    "id": "odebrecht",
    "empresa_nome": "Odebrecht",
    "empresa_setor": "Engenharia / Construção",
    "decisor_nome": "Luis Augusto Da Silva",
    "decisor_cargo": "Líder de TI",
    "decisor_tempo_empresa": "Desde dezembro de 2011",
    "faturamento_anual": "R$ 13,1–15 Bi",
    "orcamento_ti": "R$ 200–300 MM",
    "ti_percentual_receita": "1,0%",
    "crescimento_orcamento": "+20% a +30%",
    "nivel_hierarquico": "Diretoria",
    "reporte_ti": "Outra diretoria de negócio",
    "perspectiva_negocio": "Crescimento",
    "modelo_compra": "Direto com fornecedor / por categoria",
    "trimestre_investimento": "Q3 2026",
    "desafios_top6": ["Não detalhados explicitamente nos top 6"],
    "dificuldade_talentos": "Sim (escassez, senioridade, faixa salarial)",
    "maturidade_inovacao": "Emergente",
    "temas_sem_fornecedor": "Hiperautomação, Sustentabilidade/Green IT"
  },
  {
    "id": "mater_dei",
    "empresa_nome": "Rede Mater Dei de Saúde",
    "empresa_setor": "Saúde",
    "decisor_nome": "Marcello Lazzarini",
    "decisor_cargo": "Líder de TI",
    "decisor_tempo_empresa": "Desde outubro de 2020",
    "faturamento_anual": "R$ 3,1–4 Bi",
    "orcamento_ti": "R$ 100–200 MM",
    "ti_percentual_receita": "3,0%",
    "crescimento_orcamento": "Não informado",
    "nivel_hierarquico": "Não informado",
    "reporte_ti": "CEO/Presidência",
    "perspectiva_negocio": "Crescimento",
    "modelo_compra": "RFP/concorrência estruturada",
    "trimestre_investimento": "Q2 2026",
    "desafios_top6": ["IA/GenAI", "Automatizar processos", "CX/EX", "Priorizar portfólio", "Provar ROI", "Cibersegurança"],
    "dificuldade_talentos": "Não",
    "maturidade_inovacao": "Não informado",
    "temas_sem_fornecedor": "Vários temas de maturidade"
  },
  {
    "id": "motz",
    "empresa_nome": "Motz Transportes",
    "empresa_setor": "Logística / Transporte",
    "decisor_nome": "Marcelo Ortega",
    "decisor_cargo": "CIO",
    "decisor_tempo_empresa": "Desde junho de 2023",
    "faturamento_anual": "R$ 3,1–4 Bi",
    "orcamento_ti": "R$ 300–400 MM",
    "ti_percentual_receita": "10,0%",
    "crescimento_orcamento": "+10% a +20%",
    "nivel_hierarquico": "Vice-presidência",
    "reporte_ti": "CEO/Presidência",
    "perspectiva_negocio": "Crescimento",
    "modelo_compra": "Não informado",
    "trimestre_investimento": "Não informado",
    "desafios_top6": ["IA/GenAI", "Talentos", "Automatizar processos", "Cultura de inovação", "Qualidade de dados", "Provar ROI"],
    "dificuldade_talentos": "Sim (escassez, senioridade, fit cultural)",
    "maturidade_inovacao": "Estruturada",
    "temas_sem_fornecedor": "Não informado"
  },
  {
    "id": "bs2",
    "empresa_nome": "BS2",
    "empresa_setor": "Financeiro / Bancário",
    "decisor_nome": "Danilo Zimmermann",
    "decisor_cargo": "Diretor Executivo de Operações e Tecnologia",
    "decisor_tempo_empresa": "Desde janeiro de 2024",
    "faturamento_anual": "Não informado",
    "orcamento_ti": "Não informado",
    "ti_percentual_receita": "Não informado",
    "crescimento_orcamento": "Não informado",
    "nivel_hierarquico": "Não informado",
    "reporte_ti": "Não informado",
    "perspectiva_negocio": "Não informado",
    "modelo_compra": "Não informado",
    "trimestre_investimento": "Não informado",
    "desafios_top6": ["Dados insuficientes"],
    "dificuldade_talentos": "Não informado",
    "maturidade_inovacao": "Não informado",
    "temas_sem_fornecedor": "Não informado"
  },
  {
    "id": "elis",
    "empresa_nome": "Elis Group",
    "empresa_setor": "Serviços Industriais / Circulares",
    "decisor_nome": "Francisco Massaro",
    "decisor_cargo": "CIO LATAM",
    "decisor_tempo_empresa": "Desde março de 2025",
    "faturamento_anual": "Acima de R$ 15 Bi",
    "orcamento_ti": "R$ 500 MM–1 Bi",
    "ti_percentual_receita": "2,6%",
    "crescimento_orcamento": "Até +10%",
    "nivel_hierarquico": "Vice-presidência",
    "reporte_ti": "CEO/Presidência",
    "perspectiva_negocio": "Crescimento",
    "modelo_compra": "RFP/concorrência estruturada",
    "trimestre_investimento": "Q2 2026",
    "desafios_top6": ["IA/GenAI", "SRE/Observabilidade", "CX/EX", "FinOps/eficiência", "Provar ROI", "Outro"],
    "dificuldade_talentos": "Sim (faixa salarial, processo lento, localização)",
    "maturidade_inovacao": "Emergente",
    "temas_sem_fornecedor": "APIs/integração, DR, Automação/RPA, Hiperautomação, IoT"
  },
  {
    "id": "uisa",
    "empresa_nome": "UISA",
    "empresa_setor": "Agro / Biorrefinaria",
    "decisor_nome": "Rodrigo Gonçalves",
    "decisor_cargo": "Diretor de Tecnologia e Inovação",
    "decisor_tempo_empresa": "Desde junho de 2019",
    "faturamento_anual": "R$ 3,1–4 Bi",
    "orcamento_ti": "R$ 300–400 MM",
    "ti_percentual_receita": "4,0%",
    "crescimento_orcamento": "Acima de +30%",
    "nivel_hierarquico": "Diretoria",
    "reporte_ti": "CEO/Presidência",
    "perspectiva_negocio": "Crescimento",
    "modelo_compra": "RFP/concorrência estruturada",
    "trimestre_investimento": "Q2 2026",
    "desafios_top6": ["IA/GenAI", "Automatizar processos", "Sustentabilidade/green IT", "Qualidade de dados", "Modernizar infra/redes", "Provar ROI"],
    "dificuldade_talentos": "Sim (contratação e engajamento)",
    "maturidade_inovacao": "Escalonada",
    "temas_sem_fornecedor": "IA Generativa, CRM, gestão de dados"
  },
  {
    "id": "b3",
    "empresa_nome": "B3",
    "empresa_setor": "Mercado Financeiro",
    "decisor_nome": "Rodrigo Nardoni",
    "decisor_cargo": "Vice-presidente de Tecnologia e Dados",
    "decisor_tempo_empresa": "Desde março de 2017",
    "faturamento_anual": "R$ 10,1–11 Bi",
    "orcamento_ti": "R$ 200–300 MM",
    "ti_percentual_receita": "3,0%",
    "crescimento_orcamento": "Até +10%",
    "nivel_hierarquico": "Vice-presidência",
    "reporte_ti": "CEO/Presidência",
    "perspectiva_negocio": "Crescimento",
    "modelo_compra": "RFP/concorrência estruturada",
    "trimestre_investimento": "Q2 2026",
    "desafios_top6": ["SRE/Observabilidade", "CX/EX", "Qualidade de dados", "Modernizar legados", "FinOps", "Arquiteturas híbridas/multicloud"],
    "dificuldade_talentos": "Sim (contratação e engajamento — disputa salarial)",
    "maturidade_inovacao": "Emergente",
    "temas_sem_fornecedor": "Gestão de dados (sem fornecedor)"
  },
  {
    "id": "saeb",
    "empresa_nome": "SAEB",
    "empresa_setor": "Governo / Setor Público",
    "decisor_nome": "Thales Almeida",
    "decisor_cargo": "Gestor de TI",
    "decisor_tempo_empresa": "Desde outubro de 2025",
    "faturamento_anual": "R$ 9,1–10 Bi",
    "orcamento_ti": "R$ 400–500 MM",
    "ti_percentual_receita": "Não informado",
    "crescimento_orcamento": "+20% a +30%",
    "nivel_hierarquico": "Gerência",
    "reporte_ti": "CEO/Presidência",
    "perspectiva_negocio": "Crescimento",
    "modelo_compra": "Licitação pública (edital/pregão)",
    "trimestre_investimento": "Q1 2026",
    "desafios_top6": ["IA/GenAI", "Cultura de inovação", "Qualidade de dados", "Integração TI+negócio", "Modernizar legados", "Transformação digital"],
    "dificuldade_talentos": "Sim (contratação e engajamento)",
    "maturidade_inovacao": "Emergente",
    "temas_sem_fornecedor": "IA/ML, IA Generativa, APIs, DR, gestão de dados"
  },
  {
    "id": "omni",
    "empresa_nome": "Grupo Omni",
    "empresa_setor": "Aviação / Transporte Aéreo",
    "decisor_nome": "Alessandro Fernandes",
    "decisor_cargo": "CIO/CTO/CDO",
    "decisor_tempo_empresa": "Desde novembro de 2025",
    "faturamento_anual": "R$ 6,1–7 Bi",
    "orcamento_ti": "R$ 300–400 MM",
    "ti_percentual_receita": "2,0%",
    "crescimento_orcamento": "+20% a +30%",
    "nivel_hierarquico": "Vice-presidência",
    "reporte_ti": "CEO/Presidência",
    "perspectiva_negocio": "Estabilidade",
    "modelo_compra": "RFP/concorrência estruturada",
    "trimestre_investimento": "Q3 2026",
    "desafios_top6": ["IA/GenAI", "Talentos", "Cultura de inovação", "Não detalhados os demais"],
    "dificuldade_talentos": "Sim (contratação e engajamento — senioridade escassa)",
    "maturidade_inovacao": "Escalonada",
    "temas_sem_fornecedor": "Conectividade, nuvem pública, LGPD, gestão de dados"
  }
];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = companyData;
}
